name: Publish Docs

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Put your action repo here
        - uses: stephend017/pencil-pusher@v1
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
