name: deploy-prod
on:
  push:
      branches:
          - master
          
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Authenticate
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
        uses: actions/gcloud/auth@master
      - name: Build
        uses: actions/gcloud/cli@master
        with:
          args: builds submit --tag gcr.io/tippecanews/tippecanews
      - name: Deploy
        uses: actions/gcloud/cli@master
        with:
          args: beta run deploy --image gcr.io/tippecanews/tippecanews --platform managed
        
