name: deploy-prod
on:
  push:
      branches:
          - master
          
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Authenticate
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
        uses: actions/gcloud/auth@master
      - name: Build
        env:
          CLOUDSDK_CORE_PROJECT: ${{ secrets.CLOUDSDK_CORE_PROJECT }}
        uses: actions/gcloud/cli@master
        with:
          args: builds submit --tag gcr.io/tippecanews/tippecanews --quiet
      - name: Deploy
        env:
          CLOUDSDK_CORE_PROJECT: ${{ secrets.CLOUDSDK_CORE_PROJECT }}
        uses: actions/gcloud/cli@master
        with:
          args: components install beta -- quiet && gcloud beta run deploy --image gcr.io/tippecanews/tippecanews --platform managed --quiet
        
